AddMoney:
    path: /add-money
    controller: App\Wallet\Infrastructure\Controller\WalletAddMoneyController::addMoney
    methods: POST

RefundMoney:
    path: /refund-money
    controller: App\Wallet\Infrastructure\Controller\WalletRefundMoneyController::refundMoney
    methods: POST

SellItem:
    path: /sell-item
    controller: App\VendingMachine\Infrastructure\Controller\VendingMachineSellItemController::sellItem
    methods: GET

AddStock:
    path: /add-stock
    controller: App\VendingMachine\Infrastructure\Controller\VendingMachineAddStockController::addStock
    methods: POST