AddMoney:
    path: /add-money
    controller: App\Wallet\Infrastructure\Controller\WalletAddMoneyController::addMoney
    methods: POST

RefundMoney:
    path: /refund-money
    controller: App\Wallet\Infrastructure\Controller\WalletRefundMoneyController::refundMoney
    methods: POST